# Semana 9 — Lista de Prática SQL para Data Warehouse

Este notebook contém **10 exercícios progressivos** para praticar os conteúdos da Semana 9 usando o mesmo modelo de dados trabalhado em aula.

## Conteúdos praticados

- `SELECT`, `WHERE`, `ORDER BY` e `LIMIT`
- `INNER JOIN` entre fato e dimensões
- `LEFT JOIN`
- `GROUP BY`, `SUM`, `COUNT` e `AVG`
- `WHERE` antes da agregação
- `HAVING` depois da agregação
- `DATE_TRUNC` e `EXTRACT`

## Tabelas usadas

- `fato_vendas`: tabela fato com as vendas
- `dim_cliente`: dimensão com cidade e estado do cliente
- `dim_produto`: dimensão com categoria do produto
- `dim_tempo`: dimensão com datas, ano, mês, trimestre e ano/mês

> Orientação: escreva sua resposta dentro da célula de código de cada exercício, substituindo o comentário `-- escreva sua consulta aqui`.

## 1. Preparação do ambiente

Execute as células abaixo antes de iniciar os exercícios. Os arquivos `.csv` devem estar na mesma pasta deste notebook. Caso estejam em outra pasta, altere o valor da variável `BASE_PATH`.

In [1]:
# Instalação, caso esteja usando Google Colab ou ambiente sem DuckDB
# !pip install duckdb pandas

In [1]:
import pandas as pd
import duckdb
from pathlib import Path

# Altere aqui se os arquivos estiverem em outra pasta
BASE_PATH = Path('.')

dim_cliente = pd.read_csv(BASE_PATH / 'dim_cliente.csv')
dim_produto = pd.read_csv(BASE_PATH / 'dim_produto.csv')
dim_tempo = pd.read_csv(BASE_PATH / 'dim_tempo.csv')
fato_vendas = pd.read_csv(BASE_PATH / 'fato_vendas.csv')

banco_dados = duckdb.connect()
banco_dados.register('dim_cliente', dim_cliente)
banco_dados.register('dim_produto', dim_produto)
banco_dados.register('dim_tempo', dim_tempo)
banco_dados.register('fato_vendas', fato_vendas)

print('Tabelas carregadas com sucesso!')

Tabelas carregadas com sucesso!

## 2. Consulta rápida das tabelas

Use esta parte para lembrar quais colunas existem em cada tabela.

In [3]:
print('fato_vendas')
display(fato_vendas.head())

print('dim_cliente')
display(dim_cliente.head())

print('dim_produto')
display(dim_produto.head())

print('dim_tempo')
display(dim_tempo.head())

fato_vendas

,venda_sk,order_id,order_item_id,cliente_sk,produto_sk,tempo_sk,valor_produto,valor_frete,valor_total
0,1,00010242fe8c5a6d1ba2dd792cb16214,1,65558,25866,64,58.90,13.29,72.19
1,2,00018f77f2f0320c557190d7a144bdd3,1,34266,27231,125,239.90,19.93,259.83
2,3,000229ec398224ef6ca0657da4fc703e,1,34956,22625,222,199.00,17.87,216.87
3,4,00024acbcdf0a6daa1e931b038114c75,1,51764,15404,3,12.99,12.79,25.78
4,5,00042b26cf59d7ce69dfabb4e55b4fd9,1,7603,8863,512,199.90,18.14,218.04

dim_cliente

,cliente_sk,customer_id,customer_unique_id,customer_city,customer_state
0,1,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,SP
1,2,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,sao bernardo do campo,SP
2,3,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,sao paulo,SP
3,4,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,mogi das cruzes,SP
4,5,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,campinas,SP

dim_produto

,produto_sk,product_id,product_category_name,product_category_name_english
0,1,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,perfumery
1,2,3aa071139cb16b67ca9e5dea641aaa2f,artes,art
2,3,96bd76ec8810374ed1b65e291975717f,esporte_lazer,sports_leisure
3,4,cef67bcfe19066a932b7673e239eb23d,bebes,baby
4,5,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,housewares

dim_tempo

   tempo_sk        data   ano  mes  dia  trimestre  ano_mes
0         1  2017-10-02  2017   10    2          4  2017-10
1         2  2018-07-24  2018    7   24          3  2018-07
2         3  2018-08-08  2018    8    8          3  2018-08
3         4  2017-11-18  2017   11   18          4  2017-11
4         5  2018-02-13  2018    2   13          1  2018-02

# 10 exercícios de prática

## Exercício 1 🟢 — Primeiras vendas da tabela fato

Liste as **20 primeiras vendas** da tabela `fato_vendas`.

Mostre as colunas:

- `venda_sk`
- `order_id`
- `valor_produto`
- `valor_frete`
- `valor_total`

**Objetivo:** praticar `SELECT`, `FROM` e `LIMIT`.

In [ ]:
banco_dados.sql("""
-- escreva sua consulta aqui
""").df()

## Exercício 2 🟢 — Filtro com WHERE

Liste as vendas em que o `valor_total` seja **maior que 300**.

Mostre as colunas:

- `venda_sk`
- `order_id`
- `valor_total`

Ordene o resultado do **maior para o menor valor total**.

**Objetivo:** praticar `WHERE` e `ORDER BY DESC`.

In [ ]:
banco_dados.sql("""
-- escreva sua consulta aqui
""").df()

## Exercício 3 🟢 — Ranking de fretes

Liste as **15 vendas com maior valor de frete**.

Mostre as colunas:

- `venda_sk`
- `order_id`
- `valor_frete`
- `valor_total`

**Objetivo:** praticar ordenação e criação de ranking com `ORDER BY` e `LIMIT`.

In [ ]:
banco_dados.sql("""
-- escreva sua consulta aqui
""").df()

## Exercício 4 🟡 — INNER JOIN com clientes

Mostre as vendas junto com o **estado e a cidade do cliente**.

Use `INNER JOIN` entre `fato_vendas` e `dim_cliente`.

Mostre as colunas:

- `f.venda_sk`
- `f.order_id`
- `c.customer_city`
- `c.customer_state`
- `f.valor_total`

Mostre apenas 20 linhas.

**Objetivo:** praticar relacionamento entre tabela fato e dimensão cliente.

In [ ]:
banco_dados.sql("""
-- escreva sua consulta aqui
""").df()

## Exercício 5 🟡 — INNER JOIN com produto e tempo

Mostre as vendas com **categoria do produto** e **mês/ano da venda**.

Use `INNER JOIN` entre:

- `fato_vendas` e `dim_produto`
- `fato_vendas` e `dim_tempo`

Mostre as colunas:

- `f.order_id`
- `p.product_category_name_english AS categoria`
- `t.ano_mes`
- `f.valor_total`

Mostre apenas 30 linhas.

**Objetivo:** praticar mais de um `JOIN` na mesma consulta.

In [ ]:
banco_dados.sql("""
-- escreva sua consulta aqui
""").df()

## Exercício 6 🟡 — Faturamento por estado

Calcule o **faturamento total por estado do cliente**.

Use `fato_vendas` e `dim_cliente`.

A consulta deve retornar:

- `estado`
- `qtd_pedidos`, contando pedidos únicos com `COUNT(DISTINCT f.order_id)`
- `faturamento_total`, usando `SUM(f.valor_total)`
- `ticket_medio`, usando `AVG(f.valor_total)`

Ordene pelo maior faturamento.

**Objetivo:** praticar `GROUP BY`, `SUM`, `COUNT`, `AVG` e `JOIN`.

In [ ]:
banco_dados.sql("""
-- escreva sua consulta aqui
""").df()

## Exercício 7 🟡 — Receita por categoria somente em SP

Calcule a **receita por categoria de produto** considerando apenas clientes do estado de **SP**.

Use `fato_vendas`, `dim_produto` e `dim_cliente`.

A consulta deve retornar:

- `categoria`
- `qtd_pedidos`
- `receita_total`

Ordene pela maior receita.

**Objetivo:** praticar `WHERE` antes do `GROUP BY`.

In [ ]:
banco_dados.sql("""
-- escreva sua consulta aqui
""").df()

## Exercício 8 🟠 — HAVING com pedidos por estado

Liste apenas os estados com **mais de 500 pedidos únicos**.

A consulta deve retornar:

- `estado`
- `qtd_pedidos`
- `receita_total`

Ordene do maior para o menor número de pedidos.

**Objetivo:** praticar filtro de grupos com `HAVING`.

In [ ]:
banco_dados.sql("""
-- escreva sua consulta aqui
""").df()

## Exercício 9 🟠 — Receita mensal com DATE_TRUNC

Calcule o **faturamento por mês** usando `DATE_TRUNC`.

Use `fato_vendas` e `dim_tempo`.

A consulta deve retornar:

- `mes_referencia`, usando `DATE_TRUNC('month', CAST(t.data AS DATE))`
- `qtd_pedidos`
- `receita_total`

Ordene pelo mês em ordem crescente.

**Objetivo:** praticar agregação temporal com `DATE_TRUNC`.

In [ ]:
banco_dados.sql("""
-- escreva sua consulta aqui
""").df()

## Exercício 10 🔴 — Desafio BI: sazonalidade por trimestre e categoria

Monte uma análise de **receita por trimestre e categoria**.

Use `fato_vendas`, `dim_produto` e `dim_tempo`.

A consulta deve retornar:

- `ano`, usando `EXTRACT(YEAR FROM CAST(t.data AS DATE))`
- `trimestre`, usando `EXTRACT(QUARTER FROM CAST(t.data AS DATE))`
- `categoria`
- `qtd_pedidos`
- `receita_total`
- `ticket_medio`

Mostre apenas grupos com `receita_total` acima de **50000**.

Ordene por:

1. `ano`
2. `trimestre`
3. `receita_total` do maior para o menor

**Objetivo:** combinar `JOIN`, `GROUP BY`, `EXTRACT`, `HAVING` e `ORDER BY`.

In [ ]:
banco_dados.sql("""
-- escreva sua consulta aqui
""").df()

## Checklist final

Antes de entregar, confira:

- Todas as consultas executaram sem erro.
- As consultas com `JOIN` usam as chaves corretas: `cliente_sk`, `produto_sk` e `tempo_sk`.
- As consultas agregadas usam `GROUP BY` para todas as colunas não agregadas.
- Filtros antes da agregação usam `WHERE`.
- Filtros depois da agregação usam `HAVING`.
- Os resultados estão ordenados conforme o enunciado.